
networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    networks:
      - test
    volumes:
      - /project/dir:/app

  db:
    image: opavlova/db-h2
    container_name: db_h2-1
    ports:
      - "1521:1521"
    networks:
      - test
